from pathlib import Path

SEED = 42

GSM8K_PATH = "openai/gsm8k"

ROOT_DIR = Path(__file__).parents[1]

SRC_PATH = ROOT_DIR / "src"

LOGS_DIR = ROOT_DIR / "logs"

ARTIFACTS_DIR = ROOT_DIR / "artifacts"

DATA_DIR = ARTIFACTS_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
CLEANED_DATA_DIR = DATA_DIR / "cleaned"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

MODELS_DIR = ARTIFACTS_DIR / "models"

PROMPTS_DIR = ROOT_DIR / "prompts"

COT_PROMPT_PATH = PROMPTS_DIR / "cot"
COT_SYSTEM_PROMPT_PATH = COT_PROMPT_PATH / "system.txt"
COT_USER_PROMPT_PATH = COT_PROMPT_PATH / "user.txt"

LABEL_ONLY_PROMPT_PATH = PROMPTS_DIR / "label_only"
LABEL_ONLY_SYSTEM_PROMPT_PATH = LABEL_ONLY_PROMPT_PATH / "system.txt"
LABEL_ONLY_USER_PROMPT_PATH = LABEL_ONLY_PROMPT_PATH / "user.txt"

COT_USER_PROMPT = COT_USER_PROMPT_PATH.read_text()
COT_SYSTEM_PROMPT = COT_SYSTEM_PROMPT_PATH.read_text()

LABEL_ONLY_USER_PROMPT = LABEL_ONLY_USER_PROMPT_PATH.read_text()
LABEL_ONLY_SYSTEM_PROMPT = LABEL_ONLY_SYSTEM_PROMPT_PATH.read_text()
