from pathlib import Path

SEED = 42

GSM8K_PATH = "openai/gsm8k"

ROOT_DIR = Path(__file__).parents[1]

SRC_PATH = ROOT_DIR / "src"

LOGS_DIR = ROOT_DIR / "logs"

ARTIFACTS_DIR = ROOT_DIR / "artifacts"

DATA_DIR = ARTIFACTS_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
CLEANED_DATA_DIR = DATA_DIR / "cleaned"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

MODELS_DIR = ARTIFACTS_DIR / "models"

PROMPTS_DIR = ROOT_DIR / "prompts"

TEACHER_PROMPT_PATH = PROMPTS_DIR / "teacher"
TEACHER_SYSTEM_PROMPT_PATH = TEACHER_PROMPT_PATH / "system.txt"
TEACHER_USER_PROMPT_PATH = TEACHER_PROMPT_PATH / "user.txt"

TEACHER_USER_PROMPT = TEACHER_USER_PROMPT_PATH.read_text()
TEACHER_SYSTEM_PROMPT = TEACHER_SYSTEM_PROMPT_PATH.read_text()
